### ISSUE TITLE
Create a Helm Chart for WSO2 Open Banking Solution Deployment Pattern 2

### ISSUE THREAD

**Issue by kaumini** [wso2/kubernetes-open-banking#21]
**Description:**
Create resources for a Helm Chart which performs a single node deployment of the Open Banking Solution pattern 2.

**Sub tasks:**

- [x] Define deployment definitions for the product profiles (refer #15 and #16)
- [x] Define service definitions to expose the product profile services within the cluster (refer #19 and #20)
- [x] Expose the necessary product profile services to outside of the cluster (refer #18)

**Comment by kaumini** [comment]
Fixed with #26
